name: Go

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    name: CI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - name: Install mise tools
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db
      - name: Run CI
        run: mise run ci
